name: Build EXE

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name BabyKicksTracker main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BabyKicksTracker.exe
          path: dist/BabyKicksTracker.exe
